<a href="https://colab.research.google.com/github/syedaaikit/data-analyst-portfolio/blob/main/Decodelabs/data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning for **DecodeLabs**

In [24]:
import pandas as pd

In [25]:
df = pd.read_excel('Dataset for Data Analytics.xlsx')

In [26]:
import matplotlib.pyplot as plt

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [28]:
df.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

In [29]:
df.isnull().sum() / len(df) * 100

OrderID             0.00
Date                0.00
CustomerID          0.00
Product             0.00
Quantity            0.00
UnitPrice           0.00
ShippingAddress     0.00
PaymentMethod       0.00
OrderStatus         0.00
TrackingNumber      0.00
ItemsInCart         0.00
CouponCode         25.75
ReferralSource      0.00
TotalPrice          0.00
dtype: float64

In [30]:
df[df.duplicated()].shape

(0, 14)

In [31]:
df['OrderID'].value_counts()

OrderID
ORD201183    1
ORD201182    1
ORD201181    1
ORD201180    1
ORD201179    1
            ..
ORD200004    1
ORD200003    1
ORD200002    1
ORD200001    1
ORD200000    1
Name: count, Length: 1200, dtype: int64

In [32]:
df['CouponCode'] = df['CouponCode'].fillna('None')

In [33]:
df.isnull().sum() / len(df) * 100

OrderID            0.0
Date               0.0
CustomerID         0.0
Product            0.0
Quantity           0.0
UnitPrice          0.0
ShippingAddress    0.0
PaymentMethod      0.0
OrderStatus        0.0
TrackingNumber     0.0
ItemsInCart        0.0
CouponCode         0.0
ReferralSource     0.0
TotalPrice         0.0
dtype: float64